---
abstract: 'html output for Test::BDD::Cucumber'
author:
  - 'Markus Benning <ich@markusbenning.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-BDD-Cucumber-Harness-Html
requires:
  IO::File: 0
  IO::Handle: 0
  Moose: 0
  Sys::Hostname: 0
  Template: 0
  Test::BDD::Cucumber::Harness::Data: 0
  Time::HiRes: 0
  Time::Piece: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-BDD-Cucumber-Harness-Html
  repository: https://github.com/benningm/Test-BDD-Cucumber-Harness-Html
version: 1.004
